### ISSUE TITLE
大佬，请教获取活动主页面相关data数据的问题

### ISSUE THREAD

**Issue by YunYiTianCang** [ljt0515/618#16]
请问关于进入活动页面这块的js代码中的data信息是如何获取的呢？
`app.startActivity({
        action: "VIEW",
        data: 'openApp.jdMobile://virtual?params={"category":"jump","action":"to","des":"m","sourceValue":"JSHOP_SOURCE_VALUE","sourceType":"JSHOP_SOURCE_TYPE","url":"https://u.jd.com/6qkqN2X","M_sourceFrom":"mxz","msf_type":"auto"}'
    }`

**Comment by ljt0515** [comment]
看app协议
